<h1>Ideias e BrainStorm de Desenvolvimento</h1>

* Oque devemos olhar
* Quais validações são importantes para o cliente

In [1]:
import polars as pl

In [4]:
bases = '/Users/PedroFranca/Desktop/Projeto dashboard Apartamento/pasta-git-projeto-data-viz/data_viz_projeto_pbl_final.grupo-davi_pena-pedro_franca-ulisses_pena/bases/'

cartoes = pl.read_csv(f'{bases}cartoes.csv')
commits = pl.read_csv(f'{bases}commits.csv')
grupos = pl.read_csv(f'{bases}grupos.csv')
kanban_eventos = pl.read_csv(f'{bases}kanban_eventos.csv')
merge_requests = pl.read_csv(f'{bases}merge_requests.csv')
pessoas = pl.read_csv(f'{bases}pessoas.csv')
quadro_colunas = pl.read_csv(f'{bases}quadro_colunas.csv')
sprints = pl.read_csv(f'{bases}sprints.csv')

In [24]:
kanban_eventos

shape: (13_194, 6)
┌───────┬───────────────┬────────┬────────────────┬───────────┬──────────────────────────┐
│ grupo ┆ cartao_numero ┆ acao   ┆ coluna         ┆ pessoa_id ┆ ocorrido_em              │
│ ---   ┆ ---           ┆ ---    ┆ ---            ┆ ---       ┆ ---                      │
│ str   ┆ i64           ┆ str    ┆ str            ┆ str       ┆ str                      │
╞═══════╪═══════════════╪════════╪════════════════╪═══════════╪══════════════════════════╡
│ G01   ┆ 1             ┆ add    ┆ DOCUMENTATION  ┆ G01-A13   ┆ 2026-04-22T17:39:47.412Z │
│ G01   ┆ 1             ┆ add    ┆ SIZE G         ┆ G01-A13   ┆ 2026-04-22T17:39:47.412Z │
│ G01   ┆ 1             ┆ add    ┆ Backlog        ┆ G01-A13   ┆ 2026-04-22T17:40:46.797Z │
│ G01   ┆ 1             ┆ add    ┆ NEGÓCIOS       ┆ G01-A13   ┆ 2026-04-22T17:49:21.492Z │
│ G01   ┆ 1             ┆ remove ┆ Backlog        ┆ G01-A13   ┆ 2026-04-22T17:49:52.195Z │
│ …     ┆ …             ┆ …      ┆ …              ┆ …         ┆ …                        │
│ G03   ┆ 455           ┆ add    ┆ Waiting Review ┆ G03-A12   ┆ 2026-06-26T20:27:44.116Z │
│ G03   ┆ 455           ┆ remove ┆ Review         ┆ G03-A12   ┆ 2026-06-26T20:27:44.116Z │
│ G03   ┆ 455           ┆ add    ┆ Review         ┆ G03-A18   ┆ 2026-06-26T20:43:50.260Z │
│ G03   ┆ 455           ┆ remove ┆ Waiting Review ┆ G03-A18   ┆ 2026-06-26T20:43:50.260Z │
│ G03   ┆ 455           ┆ remove ┆ Review         ┆ G03-A18   ┆ 2026-06-26T21:47:39.074Z │
└───────┴───────────────┴────────┴────────────────┴───────────┴──────────────────────────┘

In [26]:
kanban = kanban_eventos.with_columns(
    pl.concat_str(pl.col('cartao_numero').cast(pl.String),pl.col('grupo')).alias('chave')
).join(
    cartoes.with_columns(
        pl.concat_str(pl.col('cartao_numero').cast(pl.String),pl.col('grupo')).alias('chave')
    ),
    on=pl.col('chave'),
    how='left'
)

kanban.write_parquet('/Users/PedroFranca/Desktop/Projeto dashboard Apartamento/pasta-git-projeto-data-viz/data_viz_projeto_pbl_final.grupo-davi_pena-pedro_franca-ulisses_pena/parquets/kanban.parquet')

In [29]:
kanban.group_by(
    pl.col('grupo'),
    pl.col('sprint')
).agg(
    pl.len().alias('quantidade cards')
).with_columns(
    pl.coalesce(pl.col('sprint'),pl.lit('Sprint Não Informado')).alias('sprint')
)

shape: (18, 3)
┌───────┬──────────────────────┬──────────────────┐
│ grupo ┆ sprint               ┆ quantidade cards │
│ ---   ┆ ---                  ┆ ---              │
│ str   ┆ str                  ┆ u32              │
╞═══════╪══════════════════════╪══════════════════╡
│ G02   ┆ Sprint 02            ┆ 946              │
│ G01   ┆ Sprint Não Informado ┆ 182              │
│ G02   ┆ Sprint 05            ┆ 1343             │
│ G03   ┆ Sprint 01            ┆ 579              │
│ G01   ┆ Sprint 03            ┆ 692              │
│ …     ┆ …                    ┆ …                │
│ G01   ┆ Sprint 04            ┆ 365              │
│ G03   ┆ Sprint 04            ┆ 1108             │
│ G01   ┆ Sprint 01            ┆ 452              │
│ G02   ┆ Sprint Não Informado ┆ 165              │
│ G03   ┆ Sprint 03            ┆ 962              │
└───────┴──────────────────────┴──────────────────┘

In [18]:
merge_requests.filter(
    pl.col('autor_id') == '[externo]'
).with_columns(
    pl.when(
        pl.col('autor_id') == '[externo]'
    ).then(
        pl.coalesce(pl.col('merged_por_id'),pl.col('revisores_ids'))
    ).alias('tratamento_responsavel_id')
)

shape: (22, 20)
┌───────┬───────────┬─────────────┬────────────┬───┬────────────┬───────────┬─────────┬────────────┐
│ grupo ┆ mr_numero ┆ titulo      ┆ descricao  ┆ … ┆ comentario ┆ sprint    ┆ rotulos ┆ tratamento │
│ ---   ┆ ---       ┆ ---         ┆ ---        ┆   ┆ s          ┆ ---       ┆ ---     ┆ _responsav │
│ str   ┆ i64       ┆ str         ┆ str        ┆   ┆ ---        ┆ str       ┆ str     ┆ el_id      │
│       ┆           ┆             ┆            ┆   ┆ i64        ┆           ┆         ┆ ---        │
│       ┆           ┆             ┆            ┆   ┆            ┆           ┆         ┆ str        │
╞═══════╪═══════════╪═════════════╪════════════╪═══╪════════════╪═══════════╪═════════╪════════════╡
│ G01   ┆ 1         ┆ docs(wad)   ┆ Paragrafo  ┆ … ┆ 0          ┆ null      ┆ null    ┆ G01-A15    │
│       ┆           ┆ adiciona    ┆ introdutor ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆ introducao  ┆ io do WAD  ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆ …           ┆            ┆   ┆            ┆           ┆         ┆            │
│ G01   ┆ 13        ┆ docs/wad/re ┆ null       ┆ … ┆ 0          ┆ null      ┆ null    ┆ G01-A14    │
│       ┆           ┆ digir-user- ┆            ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆ storys/#…   ┆            ┆   ┆            ┆           ┆         ┆            │
│ G01   ┆ 25        ┆ Docs/wad/ad ┆ null       ┆ … ┆ 0          ┆ null      ┆ null    ┆ G01-A14    │
│       ┆           ┆ iciona      ┆            ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆ modelo      ┆            ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆ logic…      ┆            ┆   ┆            ┆           ┆         ┆            │
│ G01   ┆ 29        ┆ Cria        ┆ null       ┆ … ┆ 0          ┆ null      ┆ null    ┆ G01-A14    │
│       ┆           ┆ template do ┆            ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆ arquivo     ┆            ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆ raiz …      ┆            ┆   ┆            ┆           ┆         ┆            │
│ G01   ┆ 31        ┆ Feat/g01/re ┆ Olhar com  ┆ … ┆ 0          ┆ null      ┆ null    ┆ G01-A17    │
│       ┆           ┆ formula     ┆ atencao    ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆ template    ┆            ┆   ┆            ┆           ┆         ┆            │
│ …     ┆ …         ┆ …           ┆ …          ┆ … ┆ …          ┆ …         ┆ …       ┆ …          │
│ G02   ┆ 46        ┆ Docs/corrig ┆ Corrige os ┆ … ┆ 0          ┆ Sprint 02 ┆ null    ┆ G02-A12    │
│       ┆           ┆ e erros     ┆ erros do   ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆ art2        ┆ artefato   ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆             ┆ 2…         ┆   ┆            ┆           ┆         ┆            │
│ G02   ┆ 51        ┆ Docs/review ┆ Review do  ┆ … ┆ 0          ┆ Sprint 02 ┆ null    ┆ G02-A16    │
│       ┆           ┆ art5        ┆ artefato 5 ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆             ┆ até o mom… ┆   ┆            ┆           ┆         ┆            │
│ G02   ┆ 52        ┆ Docs/review ┆ Review dos ┆ … ┆ 0          ┆ Sprint 02 ┆ null    ┆ G02-A15    │
│       ┆           ┆ art5 quinta ┆ diagramas, ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆             ┆ textos e…  ┆   ┆            ┆           ┆         ┆            │
│ G02   ┆ 54        ┆ Docs/resolv ┆ Resolve    ┆ … ┆ 0          ┆ Sprint 02 ┆ null    ┆ G02-A15    │
│       ┆           ┆ e conflito  ┆ conflito   ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆ modelage…   ┆ de         ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆             ┆ modelagem  ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆             ┆ …          ┆   ┆            ┆           ┆         ┆            │
│ G02   ┆ 57        ┆ Docs/textos ┆ Corrige    ┆ … ┆ 0          ┆ Sprint 02 ┆ null    ┆ G02-A15    │
│       ┆           ┆ diagrama    ┆ textos e   ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆ mod entid…  ┆ diagrama   ┆   ┆            ┆           ┆         ┆            │
│       ┆           ┆             ┆ mode…      ┆   ┆            ┆           ┆         ┆            │
└───────┴───────────┴─────────────┴────────────┴───┴────────────┴───────────┴─────────┴────────────┘